{% set name = "wfdb" %}
{% set version = "4.3.0" %}
{% set sha256 = "60df86bc5c9186a91930d1118218d9301d40a730ff730ec1c8571d1141d92bb9" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - numpy >=1.26.4
    - scipy >=1.13.0
    - pandas >=2.2.3
    - pysoundfile >=0.10.0
    - matplotlib-base >=3.2.2
    - requests >=2.8.1
    - fsspec >=2023.10.0
    - aiohttp >=3.10.11

test:
  requires:
    - python {{ python_min }}
  imports:
    - wfdb
    - wfdb.plot
    - wfdb.processing
    - wfdb.io

about:
  home: https://github.com/MIT-LCP/wfdb-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The WFDB Python Toolbox
  description: Native python scripts for reading and writing WFDB signals and annotations.
  doc_url: https://wfdb.readthedocs.io/en/latest/
  dev_url: https://github.com/MIT-LCP/wfdb-python

extra:
  recipe-maintainers:
    - Gijom
    - larsoner
