{% set name = "wfdb" %}
{% set version = "4.1.1" %}
{% set sha256 = "5a051714f343d9472f60cd267c679fe8d960bc27371fa625179ff4b888e5f0ce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - numpy >=1.10.1
    - scipy >=1.0.0
    - pandas >=1.3.0
    - pysoundfile >=0.10.0
    - matplotlib-base >=3.2.2
    - requests >=2.8.1

test:
  imports:
    - wfdb
    - wfdb.plot
    - wfdb.processing
    - wfdb.io

about:
  home: https://github.com/MIT-LCP/wfdb-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The WFDB Python Toolbox
  description: Native python scripts for reading and writing WFDB signals and annotations.
  doc_url: https://wfdb.readthedocs.io/en/latest/
  dev_url: https://github.com/MIT-LCP/wfdb-python

extra:
  recipe-maintainers:
    - Gijom
