{% set name = "wfdb" %}
{% set version = "3.4.1" %}
{% set sha256 = "7ae489c291e7de8bf965d3d5ae71b4117e449554b29e69b3339a69ecace4a23c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - nose >=1.3.7
  run:
    - python >=3.5
    - matplotlib-base >=3.3.4
    - nose >=1.3.7
    - numpy >=1.10.1
    - pandas >=0.17.0
    - requests >=2.8.1
    - scipy >=0.17.0

test:
  imports:
    - wfdb
    - wfdb.plot
    - wfdb.processing
    - wfdb.io

about:
  home: https://github.com/MIT-LCP/wfdb-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The WFDB Python Toolbox
  description: Native python scripts for reading and writing WFDB signals and annotations.
  doc_url: https://github.com/MIT-LCP/wfdb-python
  dev_url: https://github.com/MIT-LCP/wfdb-python

extra:
  recipe-maintainers:
    - Gijom
